# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: gatewayapi
generate:
  std-http-server: true
  strict-server: true
  models: true
  embedded-spec: true
output: "gateway/gen.go"
