name: Test

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: "Version to test."
        required: false
        default: "none"
      integration:
        type: boolean
        description: "Whether to run integration tests."
        required: false
        default: false

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Golang
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      - name: Run tests
        run: make unittest

      - name: Upload coverage report
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: go-coverage-report-${{ github.sha }}
          path: build/coverage.html

  integration-test:
    if: ${{ inputs.integration == true }}
    env:
      VERSION: ${{ inputs.VERSION }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Golang
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      - name: Run test environment
        run: make compose

      - name: Run integration tests
        run: make integrationtest

      - name: Output logs if tests fail
        if: failure()
        run: make compose-logs > build/integration-test.log

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: integration-test-log
          path: build/integration-test.log

      - name: Tear down Kerberos test environment
        if: always()
        run: make compose-down
