name: Test

on:
  workflow_call:
    inputs:
      version:
        type: string
        description: "Version to test."
        required: false
        default: "none"
      integration:
        type: boolean
        description: "Whether to run integration tests."
        required: false
        default: false

permissions:
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run tests
        run: make unittest
      - name: Upload coverage report
        uses: actions/upload-artifact@v6
        with:
          name: go-coverage-report-${{ github.sha }}
          path: coverage.html
  
  integration-test:
    if: ${{ inputs.integration == true }}
    env:
      VERSION: ${{ inputs.VERSION }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run integration tests
        run: make integrationtest
      - name: Output logs if tests fail
        if: failure()
        run: make compose-logs > build/integration-test.log
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: integration-test-logs
          path: build/integration-test.log
      - name: Tear down Kerberos test environment
        if: always()
        run: make compose-down
